name: salve_o_tcc_celular_rpg
description: Jogo RPG mobile com geolocalizacao, desbloqueio progressivo e persistencia local.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.1
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  firebase_core: ^4.8.0
  cloud_firestore: ^6.4.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/ambiente_praca/
    - assets/images/ambiente_biblioteca/
    - assets/images/ambiente_capela/
    - assets/images/ambiente_h15/
    - assets/images/ambiente_sala_10a/
    - assets/data/
