// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO-ERHsB5j2MFUKnuaaKuVpJhlIQa-H7Y',
    appId: '1:263771560876:web:2dc7553f4b60cc8e46f809',
    messagingSenderId: '263771560876',
    projectId: 'salve-o-tcc',
    authDomain: 'salve-o-tcc.firebaseapp.com',
    storageBucket: 'salve-o-tcc.firebasestorage.app',
    measurementId: 'G-H741E6GS0D',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO-ERHsB5j2MFUKnuaaKuVpJhlIQa-H7Y',
    appId: '1:263771560876:web:2dc7553f4b60cc8e46f809',
    messagingSenderId: '263771560876',
    projectId: 'salve-o-tcc',
    authDomain: 'salve-o-tcc.firebaseapp.com',
    storageBucket: 'salve-o-tcc.firebasestorage.app',
    measurementId: 'G-H741E6GS0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkfcteYPkVyYdOYfm9VZrFtazyYfekFsY',
    appId: '1:263771560876:android:5407f9fc7f0ac45946f809',
    messagingSenderId: '263771560876',
    projectId: 'salve-o-tcc',
    storageBucket: 'salve-o-tcc.firebasestorage.app',
  );

}